### ISSUE TITLE
class ProxyWebSocket extends WebSocket {

### ISSUE THREAD

**Issue by chinlee1523** [erictik/midjourney-discord#2]
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/chin/lizhishidai/midjourneyapi/src/api/api.service.ts:27:30)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/Users/chin/lizhishidai/midjourneyapi/src/api/api.controller.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1309:10)

**Comment by zcpua** [comment]
Please provide more error information and recurring code

**Comment by zcpua** [comment]
and node.js version
